### ISSUE TITLE
游戏—围住神经猫

### ISSUE THREAD

**Issue by Leo-ZLC** [hzuapps/android-labs#139]
简单版的围住神经猫游戏的背景是一排排的圆圈，可以用二维数组创建，而这些圆圈有三种状态，分别为猫可以走并可以设置路障的位置（灰色），猫所处的位置（红色），猫不能走并已开启路障的位置（橘色），这些状态定义在Dot类中，显然其应该有坐标X和Y；游戏的背景等我都放在Playground类中，背景是基于SurfaceView开发的，而里面还有很多功能，如猫和已设路障的初始化位置，猫如何躲路障，如何判断路可走，判断处在边界位置等等；最后在Activity中调用Playground。

**Comment by zengsn** [comment]
把题目描述写一下，下节课找老师

**Comment by zengsn** [comment]
步骤写在这里 https://github.com/zengsn/android-experiment-guide/blob/master/lab4.md
