### ISSUE TITLE
RSS阅读器

### ISSUE THREAD

**Issue by freedom0** [hzuapps/android-labs#150]
功能：订阅感兴趣的新闻，博客，获取最新的消息，一旦有了更新，RSS会自动提醒

**Comment by freedom0** [comment]
1.搭建 Android Wear 开发环境
2.在 Android Wear 中创建 Notification
3.在 Android Wear 中调用 Google 语音识别
4.调用和解析图灵机器人 API
5.Android Wear 与手机进行数据同步
6.创建 Google API Client
7.使用 DataAPI 监听 DataItem 的变化

**Comment by zengsn** [comment]
重点写RSS获取的网络编程部分。抓紧时间做。

**Comment by zengsn** [comment]
https://github.com/zengsn/android-experiment-guide/blob/master/lab7.md
