### ISSUE TITLE
新建客户信息表单

### ISSUE THREAD

**Issue by Niangao-Warren** [hzuapps/android-labs#162]
新建客户表单，填写姓名、微信、性别及公司，点击提交，界面会显示所填的信息
若有一项没填写，点击提交后，界面会提示没有填写的那一项
性别选项中，Switch调用OnCheckedChanged监听事件来判断男女，false为男（默认），True=女
公司选项中，Spinner用ArrayAdapter来填充了一些字符串数据到了适配器中呈现出来，然后用setOnItemSelectedListener来监听用户的选择，并获取值

**Comment by sakcmhhjjkk5** [comment]
计算机一班

**Comment by sakcmhhjjkk5** [comment]
新建客户表单，填写姓名、微信、性别及公司，点击提交，界面会显示所填的信息
若有一项没填写，点击提交后，界面会提示没有填写的那一项
性别选项中，Switch调用OnCheckedChanged监听事件来判断男女，false为男（默认），True=女
公司选项中，Spinner用ArrayAdapter来填充了一些字符串数据到了适配器中呈现出来，然后用setOnItemSelectedListener来监听用户的选择，并获取值
