### ISSUE TITLE
仿微信主界面

### ISSUE THREAD

**Issue by findsomeoneyys** [hzuapps/android-labs#208]
1.底下有四个按钮，点击分别会切换到聊天，联系人，发现，我
2.点击聊天记录或者联系人一栏会推入聊天界面
3.点击发现再点朋友圈推入朋友圈界面
4.我界面里面可以设置自己的头像跟一些设置

**Comment by zengsn** [comment]
你是哪一个班的？

**Comment by findsomeoneyys** [comment]
计师1班

**Comment by zengsn** [comment]
把你做这个界面的步骤写到这里吧 
https://github.com/zengsn/android-experiment-guide/blob/master/lab4.md

下一节课，我告诉你怎么写。
