### ISSUE TITLE
语音记账助手

### ISSUE THREAD

**Issue by DUDUfine** [hzuapps/android-labs#257]
界面：
1、界面上有一个按钮，按下说话可进行录音，然后转换为文字；
2、利用ListView将每一次消费记录保存下来，记录包括消费内容+时间
3、每一条记录右下角有一个删除按钮；
实现方案：
1、利用SDK嵌入APP，配置xml，调用接口将语言转换为文字；
2、利用 sqlite进行数据存储，进行数据增删查改操作。

**Comment by zengsn** [comment]
写一个录音的实例步骤 、调百度音频文件转文字 （Markdown）

https://github.com/zengsn/android-experiment-guide/blob/master/lab8.md
