### ISSUE TITLE
基于Android平台的个人理财软件的设计与实现

### ISSUE THREAD

**Issue by linyuehuan24** [hzuapps/android-labs#295]
1.用户账户的注册、用户切换、用户名密码修改、账户删除，语音识别
记账。
2收入信息的增删改，支出信息的增删改，收入类型的增删，支
出类型的增删，收入信息分类统计，支出信息分类统计，收入支出总
额统计。
3.数据还原、清空等等。

**Comment by zengsn** [comment]
要来找老师检查才算完成。你这样就交一次实验是不及格的。

**Comment by linyuehuan24** [comment]
老师，现在我的实验已经完成了，需要检查

**Comment by linyuehuan24** [comment]
@zengsn 老师，这个我做完了，需要在哪里给你检查

**Comment by linyuehuan24** [comment]
@zengsn 老师，这是我之前的一个题目，实验1-3就是在这里做的，不过在中途的时候换题目了，但是在最后的时候因为那个换了题目的感觉对我来说有难度，所以做回来了之前的实验，这次实验的1-9都有完成，不过还没完成检查，老师，有时间检查吗

**Comment by zengsn** [comment]
检查是在上课时间的

**Comment by linyuehuan24** [comment]
曾老师，上课时间过了，那现在还可以检查吗，我实验1-9是有完成的。
