### ISSUE TITLE
海贼王连连看游戏

### ISSUE THREAD

**Issue by wmll** [hzuapps/android-labs#296]
简单的实现海贼王连连看游戏,里面有卡通海贼王路飞等人物。
操作方法
鼠标左键点击两个相同的图案，如果图案之间的连线转折不超过2次且不经过其他图案，即可消除。注        意：如果找不出相同的图片可以使用提示和洗牌按钮。
游戏目标
在限定时间内消除所有相同图片。
在限定的时间内消除所有图片，即可进入下一关！

**Comment by wmll** [comment]
#网一

**Comment by zengsn** [comment]
请把练练看的界面设计步骤编写到这里：https://github.com/zengsn/android-experiment-guide/blob/master/lab4.md
