### ISSUE TITLE
安卓游戏：黑白棋

### ISSUE THREAD

**Issue by yjf2213939** [hzuapps/android-labs#395]
黑白棋，又叫翻转棋（Reversi）、奥赛罗棋（Othello）、苹果棋或反棋（Anti reversi）。游戏通过相互翻转对方的棋子，最后以棋盘上谁的棋子多来判断胜负。在安卓环境下实现黑白棋的应用。

**Comment by zengsn** [comment]
除了界面，有没有存储或网络功能？

**Comment by yjf2213939** [comment]
老师，没有了。

**Comment by zengsn** [comment]
步骤编辑到这里：https://github.com/zengsn/android-experiment-guide/blob/master/lab4.md
