### ISSUE TITLE
仿"你画我猜"画板功能

### ISSUE THREAD

**Issue by qingtian1993** [hzuapps/android-labs#43]
1：玩家可以在画板上画任何东西
2：改变画笔颜色
3：改变画笔大小
4：增加图片保存功能

**Comment by qingtian1993** [comment]
1：玩家可以在画板上画任何东西
2：改变画笔颜色
3：改变画笔大小
4：增加图片保存功能

**Comment by zengsn** [comment]
把你的实验例子，写一个操作实例“将文件存储到SD卡”到这里：
https://github.com/zengsn/android-experiment-guide/blob/master/lab5.md 

下一节课和你聊。
