### ISSUE TITLE
猜拳游戏

### ISSUE THREAD

**Issue by wangrunyu** [hzuapps/android-labs#55]
1、第一个activity显示“开始游戏”“游戏数据”等选项。
2、点击“游戏数据”时转到另一个activity显示胜利场数、失败场数、平手场数，胜率等数据。并有一个“返回首页”的选项，点击后返回到一开始的activity。
3、点击“开始游戏”后转到另外一个activity，选择自己要出剪刀，石头或布后，系统也会随机出拳，然后提示你是输了还是赢了。该界面也有一个“返回首页”的选项，点击后返回一开始的activity。

（备用功能）4、实现后考虑加上可以切换玩家的功能，就是不同玩家登录自己账号后会显示自己的数据。

**Comment by wangrunyu** [comment]
13计师2班 王润宇 29

**Comment by zengsn** [comment]
你不用填姓名学号，按照要求做实验，我自然知道你的学号。另外，只交一次实验是不及格的。
