### ISSUE TITLE
节日短信

### ISSUE THREAD

**Issue by JERR-lxm** [hzuapps/android-labs#550]
节日短信：1、选择相应节日，进入已编辑好的短信选择界面
                  2、浏览发送记录
                  3、选择相应短信并编辑，添加联系人，发送

**Comment by JERR-lxm** [comment]
节日短信：1、选择相应节日，进入已编辑好的短信选择界面
                  2、浏览发送记录
                  3、选择相应短信并编辑，添加联系人，发送

**Comment by JERR-lxm** [comment]
老师，要是改了AndoridManifest要怎么传？

**Comment by zengsn** [comment]
传到自己的目录下。参见其他同学的作业。
