### ISSUE TITLE
手机控制电脑关机、重启 - 基于Socket通信

### ISSUE THREAD

**Issue by loveincloud** [hzuapps/android-labs#58]
1、手机socket客户端通过获取手机wifi的IP地址对该IP地址所在网段进行扫描尝试连接PC上的socket服务端，如果该网段内有可连接的PC服务端，则把成功连接服务端的IP地址保存到UI主线程的ip变量上并显示在界面中的TextView中，同时通过Toast显示“扫描到PC服务端IP地址”。
2、通过点击界面中的“CONNECT”按钮，用扫描得到的IP地址连接服务端，并用Toast提示连接到PC服务端。
3、在连接服务端后，点击“SHUTDOWN”或“RESTART”按钮，发送约定好的字符串，令PC机关机或重启。点击“CANCEL”按钮，发送约定好的字符串，令PC机取消关机、重启命令。

**Comment by zengsn** [comment]
填写实验内容描述

**Comment by loveincloud** [comment]
在哪里填写？
