### ISSUE TITLE
TCP测试工具

### ISSUE THREAD

**Issue by HauyuChen** [hzuapps/android-labs#63]
*\* 名称 **
TCP测试工具

*\* 功能 **
1. 模拟TCP服务端：通过本程序，监听本地端口，等待客户端连接；若连接成功，可实现服务端和客户端之间的数据收发；
2. 模拟TCP客户端：通过本程序，连接TCP服务端；若连接成功，可实现客户端和服务端之间的数据收发。

*\* 描述 **
本程序可作为socket开发的测试工具，通过本程序测试自己编写的服务端或客户端功能是否符合要求。

**Comment by zengsn** [comment]
描述一下实验内容

**Comment by ChenHauyu** [comment]
** 名称 **
TCP测试工具

** 功能 **
1. 模拟TCP服务端：通过本程序，监听本地端口，等待客户端连接；若连接成功，可实现服务端和客户端之间的数据收发；
2. 模拟TCP客户端：通过本程序，连接TCP服务端；若连接成功，可实现客户端和服务端之间的数据收发。

** 描述 **
本程序可作为socket开发的测试工具，通过本程序测试自己编写的服务端或客户端功能是否符合要求。

**Comment by zengsn** [comment]
写在最上面
