### ISSUE TITLE
PC通信客户端

### ISSUE THREAD

**Issue by dbz26** [hzuapps/android-labs#72]
与windows上的socket服务器通过文字信息进行通信。

**Comment by zengsn** [comment]
Socket编程步骤写在这里 https://github.com/zengsn/android-experiment-guide/edit/master/lab7.md

**Comment by dbz26** [comment]
老师，那个socket编程的编程步骤已经有人写了，您上次叫我写的socket客户端的连接和接收消息还用写上去吗？ @zengsn
