### ISSUE TITLE
英语四级单选助手答题类

### ISSUE THREAD

**Issue by linyuehuan24** [hzuapps/android-labs#723]
1.本APP是一个自我测试的软件
2.考题有练习部分和模拟考试部分，练习部分会逐条显示考题
3.点击选择题目可以查看所有正确错误和未答的选项，点击序号即可进入答题
4.本项目备份了一份json格式的题库在压缩包里

**Comment by linyuehuan24** [comment]
@zengsn 老师，这个题目是我换过后的题目，然后我做不太好，所以我做了以前的那个题目，以前的那个题目实验1-9都完成了，不过还没被老师你检查通过

**Comment by zengsn** [comment]
哪个题目？

**Comment by linyuehuan24** [comment]
题目是《基于Android平台的个人理财软件的设计与实现》。
