### ISSUE TITLE
游戏--就踩白块

### ISSUE THREAD

**Issue by benguadesenlin** [hzuapps/android-labs#83]
该游戏界面会有5*5的小黑块，然后系统会随机生成一定数量的小白块，玩家点击白块加分，点击黑块扣分。游戏结束后会判断该局游戏分数，如为历史最高，则保存该记录，下次进入游戏时将该分数显示到最高分数位置。

**Comment by zengsn** [comment]
请添加实验内容描述

**Comment by zengsn** [comment]
步骤编写到这里 https://github.com/zengsn/android-experiment-guide/blob/master/games.md

**Comment by benguadesenlin** [comment]
步骤写好了、老师看下
